In [190]:
# Prepare your data (e.g. load and tokenize your dataset)
import pandas as pd 
dataset=pd.read_csv('Diabetes.csv')
dataset.head

<bound method NDFrame.head of       rowID             race  gender      age   weight admission_type_id  \
0         1        Caucasian  Female  [50-60)        ?          Elective
1         2        Caucasian  Female  [20-30)  [50-75)            Urgent
2         3        Caucasian    Male  [80-90)        ?     Not Available
3         4  AfricanAmerican  Female  [50-60)        ?         Emergency
4         5  AfricanAmerican  Female  [50-60)        ?         Emergency
...     ...              ...     ...      ...      ...               ...
9995   9996        Caucasian  Female  [60-70)        ?          Elective
9996   9997  AfricanAmerican    Male  [60-70)        ?            Urgent
9997   9998  AfricanAmerican  Female  [70-80)        ?         Emergency
9998   9999        Caucasian    Male  [80-90)        ?            Urgent
9999  10000        Caucasian    Male  [70-80)        ?          Elective

                               discharge_disposition_id  \
0                                    Discharged to home
1                                    Discharged to home
2     Discharged/transferred to home with home healt...
3                                    Discharged to home
4                                    Discharged to home
...                                                 ...
9995  Discharged/transferred to home with home healt...
9996                      Discharged/transferred to SNF
9997  Discharged/transferred to home with home healt...
9998                      Discharged/transferred to SNF
9999                                 Discharged to home

                             admission_source_id  time_in_hospital payer_code  \
0                             Physician Referral                 1         CP
1                             Physician Referral                 2         UN
2                                            NaN                 7         MC
3     Transfer from another health care facility                 4         UN
4                                 Emergency Room                 5          ?
...                                          ...               ...        ...
9995                          Physician Referral                 3         MC
9996                              Emergency Room                 8         CM
9997                              Emergency Room                13          ?
9998                              Emergency Room                 2         MC
9999                          Physician Referral                 8          ?

      ... glipizide.metformin  glimepiride.pioglitazone  \
0     ...                  No                        No
1     ...                  No                        No
2     ...                  No                        No
3     ...                  No                        No
4     ...                  No                        No
...   ...                 ...                       ...
9995  ...                  No                        No
9996  ...                  No                        No
9997  ...                  No                        No
9998  ...                  No                        No
9999  ...                  No                        No

      metformin.rosiglitazone  metformin.pioglitazone  change  diabetesMed  \
0                          No                      No      No           No
1                          No                      No      No           No
2                          No                      No      No          Yes
3                          No                      No      No          Yes
4                          No                      No      Ch          Yes
...                       ...                     ...     ...          ...
9995                       No                      No      Ch          Yes
9996                       No                      No      Ch          Yes
9997                       No                      No      No           No
9998                       No                      No      No           No
9999                       No                      No      Ch          Yes

      readmitted                                        diag_1_desc  \
0          False                 Spinal stenosis in cervical region
1          False  First-degree perineal laceration, unspecified ...
2           True  Pneumococcal pneumonia [Streptococcus pneumoni...
3          False                     Cellulitis and abscess of face
4          False  Bipolar I disorder, single manic episode, unsp...
...          ...                                                ...
9995       False      Osteoarthrosis, generalized, site unspecified
9996       False    Acute, but ill-defined, cerebrovascular disease
9997        True                           Streptococcal septicemia
9998       False     Acute gastritis, without mention of hemorrhage
9999       False              Congestive heart failure, unspecified

                                            diag_2_desc  \
0                    Spinal stenosis in cervical region
1     Diabetes mellitus of mother, complicating preg...
2                 Congestive heart failure, unspecified
3     Streptococcus infection in conditions classifi...
4     Diabetes mellitus without mention of complicat...
...                                                 ...
9995                   Malignant essential hypertension
9996  Diabetes mellitus without mention of complicat...
9997                       Chronic kidney disease (ckd)
9998               Hyperosmolality and/or hypernatremia
9999  Hypertensive chronic kidney disease, malignant...

                                            diag_3_desc
0                   Effusion of joint, site unspecified
1                                  Sideroblastic anemia
2                  Hyperosmolality and/or hypernatremia
3     Diabetes mellitus without mention of complicat...
4                             Depressive type psychosis
...                                                 ...
9995                          Pure hypercholesterolemia
9996             Fitting and adjustment of other device
9997                                       Achlorhydria
9998        Urinary tract infection, site not specified
9999            Paroxysmal supraventricular tachycardia

[10000 rows x 52 columns]>

In [191]:
dataset.describe

<bound method NDFrame.describe of       rowID             race  gender      age   weight admission_type_id  \
0         1        Caucasian  Female  [50-60)        ?          Elective
1         2        Caucasian  Female  [20-30)  [50-75)            Urgent
2         3        Caucasian    Male  [80-90)        ?     Not Available
3         4  AfricanAmerican  Female  [50-60)        ?         Emergency
4         5  AfricanAmerican  Female  [50-60)        ?         Emergency
...     ...              ...     ...      ...      ...               ...
9995   9996        Caucasian  Female  [60-70)        ?          Elective
9996   9997  AfricanAmerican    Male  [60-70)        ?            Urgent
9997   9998  AfricanAmerican  Female  [70-80)        ?         Emergency
9998   9999        Caucasian    Male  [80-90)        ?            Urgent
9999  10000        Caucasian    Male  [70-80)        ?          Elective

                               discharge_disposition_id  \
0                                    Discharged to home
1                                    Discharged to home
2     Discharged/transferred to home with home healt...
3                                    Discharged to home
4                                    Discharged to home
...                                                 ...
9995  Discharged/transferred to home with home healt...
9996                      Discharged/transferred to SNF
9997  Discharged/transferred to home with home healt...
9998                      Discharged/transferred to SNF
9999                                 Discharged to home

                             admission_source_id  time_in_hospital payer_code  \
0                             Physician Referral                 1         CP
1                             Physician Referral                 2         UN
2                                            NaN                 7         MC
3     Transfer from another health care facility                 4         UN
4                                 Emergency Room                 5          ?
...                                          ...               ...        ...
9995                          Physician Referral                 3         MC
9996                              Emergency Room                 8         CM
9997                              Emergency Room                13          ?
9998                              Emergency Room                 2         MC
9999                          Physician Referral                 8          ?

      ... glipizide.metformin  glimepiride.pioglitazone  \
0     ...                  No                        No
1     ...                  No                        No
2     ...                  No                        No
3     ...                  No                        No
4     ...                  No                        No
...   ...                 ...                       ...
9995  ...                  No                        No
9996  ...                  No                        No
9997  ...                  No                        No
9998  ...                  No                        No
9999  ...                  No                        No

      metformin.rosiglitazone  metformin.pioglitazone  change  diabetesMed  \
0                          No                      No      No           No
1                          No                      No      No           No
2                          No                      No      No          Yes
3                          No                      No      No          Yes
4                          No                      No      Ch          Yes
...                       ...                     ...     ...          ...
9995                       No                      No      Ch          Yes
9996                       No                      No      Ch          Yes
9997                       No                      No      No           No
9998                       No                      No      No           No
9999                       No                      No      Ch          Yes

      readmitted                                        diag_1_desc  \
0          False                 Spinal stenosis in cervical region
1          False  First-degree perineal laceration, unspecified ...
2           True  Pneumococcal pneumonia [Streptococcus pneumoni...
3          False                     Cellulitis and abscess of face
4          False  Bipolar I disorder, single manic episode, unsp...
...          ...                                                ...
9995       False      Osteoarthrosis, generalized, site unspecified
9996       False    Acute, but ill-defined, cerebrovascular disease
9997        True                           Streptococcal septicemia
9998       False     Acute gastritis, without mention of hemorrhage
9999       False              Congestive heart failure, unspecified

                                            diag_2_desc  \
0                    Spinal stenosis in cervical region
1     Diabetes mellitus of mother, complicating preg...
2                 Congestive heart failure, unspecified
3     Streptococcus infection in conditions classifi...
4     Diabetes mellitus without mention of complicat...
...                                                 ...
9995                   Malignant essential hypertension
9996  Diabetes mellitus without mention of complicat...
9997                       Chronic kidney disease (ckd)
9998               Hyperosmolality and/or hypernatremia
9999  Hypertensive chronic kidney disease, malignant...

                                            diag_3_desc
0                   Effusion of joint, site unspecified
1                                  Sideroblastic anemia
2                  Hyperosmolality and/or hypernatremia
3     Diabetes mellitus without mention of complicat...
4                             Depressive type psychosis
...                                                 ...
9995                          Pure hypercholesterolemia
9996             Fitting and adjustment of other device
9997                                       Achlorhydria
9998        Urinary tract infection, site not specified
9999            Paroxysmal supraventricular tachycardia

[10000 rows x 52 columns]>

In [192]:
dataset.isnull().sum()

rowID                         0
race                          0
gender                        0
age                           0
weight                        0
admission_type_id           721
discharge_disposition_id    469
admission_source_id         936
time_in_hospital              0
payer_code                    0
medical_specialty             0
num_lab_procedures            0
num_procedures                0
num_medications               0
number_outpatient             0
number_emergency              0
number_inpatient              0
diag_1                        0
diag_2                        0
diag_3                        0
number_diagnoses              0
max_glu_serum                 0
A1Cresult                     0
metformin                     0
repaglinide                   0
nateglinide                   0
chlorpropamide                0
glimepiride                   0
acetohexamide                 0
glipizide                     0
glyburide                     0
tolbutamide                   0
pioglitazone                  0
rosiglitazone                 0
acarbose                      0
miglitol                      0
troglitazone                  0
tolazamide                    0
examide                       0
citoglipton                   0
insulin                       0
glyburide.metformin           0
glipizide.metformin           0
glimepiride.pioglitazone      0
metformin.rosiglitazone       0
metformin.pioglitazone        0
change                        0
diabetesMed                   0
readmitted                    0
diag_1_desc                   2
diag_2_desc                  59
diag_3_desc                 208
dtype: int64

In [193]:
dataset=dataset.dropna()
dataset.isnull().sum()

rowID                       0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide.metformin         0
glipizide.metformin         0
glimepiride.pioglitazone    0
metformin.rosiglitazone     0
metformin.pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
diag_1_desc                 0
diag_2_desc                 0
diag_3_desc                 0
dtype: int64

In [194]:
dataset=dataset.drop(['diag_1_desc','citoglipton','glyburide.metformin','metformin.rosiglitazone','metformin.pioglitazone','glimepiride.pioglitazone','acetohexamide','max_glu_serum','glipizide','glyburide','tolbutamide','tolazamide','pioglitazone','troglitazone','rosiglitazone','miglitol','acarbose','chlorpropamide','glimepiride','A1Cresult','metformin','repaglinide','nateglinide','weight','payer_code','diag_2_desc','diag_3_desc','change','rowID','admission_type_id','discharge_disposition_id','admission_source_id','diag_1','diag_2','diag_3'],axis=1)

In [195]:
dataset['race'].value_counts()

Caucasian          5855
AfricanAmerican    1787
?                   189
Hispanic            129
Other                95
Asian                43
Name: race, dtype: int64

In [196]:
def clean_race(x):
    if 'Caucasian' in x:
        return 'Caucasian'
    if 'AfricanAmerican' in x:
        return 'AfricanAmerican'
    if 'Hispanic' in x:
        return 'Hispanic'
    if 'Asian' in x:
        return 'Asian'
    return 'Other'
dataset['race']=dataset['race'].apply(clean_race)
dataset

,race,gender,age,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,examide,insulin,glipizide.metformin,diabetesMed,readmitted
0,Caucasian,Female,[50-60),1,Surgery-Neuro,35,4,21,0,0,0,9,No,No,No,No,False
1,Caucasian,Female,[20-30),2,?,8,5,5,0,0,0,6,No,No,No,No,False
3,AfricanAmerican,Female,[50-60),4,?,33,1,5,0,0,0,3,No,Steady,No,Yes,False
4,AfricanAmerican,Female,[50-60),5,Psychiatry,31,0,13,0,0,0,7,No,Steady,No,Yes,False
5,Caucasian,Male,[70-80),4,Cardiology,29,0,10,0,0,0,8,No,No,No,Yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Caucasian,Female,[60-70),3,?,30,1,29,0,0,0,7,No,No,No,Yes,False
9996,AfricanAmerican,Male,[60-70),8,Emergency/Trauma,1,5,15,0,0,0,9,No,Steady,No,Yes,False
9997,AfricanAmerican,Female,[70-80),13,InternalMedicine,46,2,14,0,0,1,6,No,No,No,No,True
9998,Caucasian,Male,[80-90),2,InternalMedicine,62,1,7,0,0,3,9,No,No,No,No,False
9999,Caucasian,Male,[70-80),8,?,61,0,18,0,0,1,9,No,No,No,Yes,False

In [197]:
dataset['age'].value_counts()

[70-80)     2092
[60-70)     1795
[50-60)     1413
[80-90)     1308
[40-50)      799
[30-40)      315
[90-100)     210
[20-30)      111
[10-20)       44
[0-10)        11
Name: age, dtype: int64

In [198]:
def clean_age(x):
    if '[70-80)' in x:
        return '75'
    if '[60-70)' in x:
        return '65'
    if '[50-60)' in x:
        return '55'
    if '[80-90)' in x:
        return '85'
    if '[40-50)' in x:
        return '45'
    if '[30-40)' in x:
        return '35'
    if '[20-30)' in x:
        return '25'
    if '[10-20)' in x:
        return '15'

    return '5'
dataset['age']=dataset['age'].apply(clean_age)
dataset

,race,gender,age,time_in_hospital,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,examide,insulin,glipizide.metformin,diabetesMed,readmitted
0,Caucasian,Female,55,1,Surgery-Neuro,35,4,21,0,0,0,9,No,No,No,No,False
1,Caucasian,Female,25,2,?,8,5,5,0,0,0,6,No,No,No,No,False
3,AfricanAmerican,Female,55,4,?,33,1,5,0,0,0,3,No,Steady,No,Yes,False
4,AfricanAmerican,Female,55,5,Psychiatry,31,0,13,0,0,0,7,No,Steady,No,Yes,False
5,Caucasian,Male,75,4,Cardiology,29,0,10,0,0,0,8,No,No,No,Yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Caucasian,Female,65,3,?,30,1,29,0,0,0,7,No,No,No,Yes,False
9996,AfricanAmerican,Male,65,8,Emergency/Trauma,1,5,15,0,0,0,9,No,Steady,No,Yes,False
9997,AfricanAmerican,Female,75,13,InternalMedicine,46,2,14,0,0,1,6,No,No,No,No,True
9998,Caucasian,Male,85,2,InternalMedicine,62,1,7,0,0,3,9,No,No,No,No,False
9999,Caucasian,Male,75,8,?,61,0,18,0,0,1,9,No,No,No,Yes,False

In [199]:
dataset['num_lab_procedures'].value_counts()

43     260
38     222
1      208
44     203
45     201
      ...
109      1
104      1
113      1
108      1
97       1
Name: num_lab_procedures, Length: 102, dtype: int64

In [200]:
dataset=dataset.rename({"medical_specialty":"specialty"},axis=1)

In [201]:
def clean_medical_specialty(x):
    if '?' in x:
        return 'Non medical'
    return 'Medical'
dataset['specialty']=dataset['specialty'].apply(clean_medical_specialty)
dataset

,race,gender,age,time_in_hospital,specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,examide,insulin,glipizide.metformin,diabetesMed,readmitted
0,Caucasian,Female,55,1,Medical,35,4,21,0,0,0,9,No,No,No,No,False
1,Caucasian,Female,25,2,Non medical,8,5,5,0,0,0,6,No,No,No,No,False
3,AfricanAmerican,Female,55,4,Non medical,33,1,5,0,0,0,3,No,Steady,No,Yes,False
4,AfricanAmerican,Female,55,5,Medical,31,0,13,0,0,0,7,No,Steady,No,Yes,False
5,Caucasian,Male,75,4,Medical,29,0,10,0,0,0,8,No,No,No,Yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Caucasian,Female,65,3,Non medical,30,1,29,0,0,0,7,No,No,No,Yes,False
9996,AfricanAmerican,Male,65,8,Medical,1,5,15,0,0,0,9,No,Steady,No,Yes,False
9997,AfricanAmerican,Female,75,13,Medical,46,2,14,0,0,1,6,No,No,No,No,True
9998,Caucasian,Male,85,2,Medical,62,1,7,0,0,3,9,No,No,No,No,False
9999,Caucasian,Male,75,8,Non medical,61,0,18,0,0,1,9,No,No,No,Yes,False

In [202]:
dataset.head

<bound method NDFrame.head of                  race  gender age  time_in_hospital    specialty  \
0           Caucasian  Female  55                 1      Medical
1           Caucasian  Female  25                 2  Non medical
3     AfricanAmerican  Female  55                 4  Non medical
4     AfricanAmerican  Female  55                 5      Medical
5           Caucasian    Male  75                 4      Medical
...               ...     ...  ..               ...          ...
9995        Caucasian  Female  65                 3  Non medical
9996  AfricanAmerican    Male  65                 8      Medical
9997  AfricanAmerican  Female  75                13      Medical
9998        Caucasian    Male  85                 2      Medical
9999        Caucasian    Male  75                 8  Non medical

      num_lab_procedures  num_procedures  num_medications  number_outpatient  \
0                     35               4               21                  0
1                      8               5                5                  0
3                     33               1                5                  0
4                     31               0               13                  0
5                     29               0               10                  0
...                  ...             ...              ...                ...
9995                  30               1               29                  0
9996                   1               5               15                  0
9997                  46               2               14                  0
9998                  62               1                7                  0
9999                  61               0               18                  0

      number_emergency  number_inpatient  number_diagnoses examide insulin  \
0                    0                 0                 9      No      No
1                    0                 0                 6      No      No
3                    0                 0                 3      No  Steady
4                    0                 0                 7      No  Steady
5                    0                 0                 8      No      No
...                ...               ...               ...     ...     ...
9995                 0                 0                 7      No      No
9996                 0                 0                 9      No  Steady
9997                 0                 1                 6      No      No
9998                 0                 3                 9      No      No
9999                 0                 1                 9      No      No

     glipizide.metformin diabetesMed  readmitted
0                     No          No       False
1                     No          No       False
3                     No         Yes       False
4                     No         Yes       False
5                     No         Yes       False
...                  ...         ...         ...
9995                  No         Yes       False
9996                  No         Yes       False
9997                  No          No        True
9998                  No          No       False
9999                  No         Yes       False

[8098 rows x 17 columns]>

In [203]:
dataset['num_lab_procedures'].value_counts()

43     260
38     222
1      208
44     203
45     201
      ...
109      1
104      1
113      1
108      1
97       1
Name: num_lab_procedures, Length: 102, dtype: int64

In [204]:
from sklearn.preprocessing import LabelEncoder

In [205]:
l_race=LabelEncoder()
dataset['race']=l_race.fit_transform(dataset['race'])
l_gender=LabelEncoder()
dataset['gender']=l_gender.fit_transform(dataset['gender'])
l_specialty=LabelEncoder()
dataset['specialty']=l_specialty.fit_transform(dataset['specialty'])
l_examide=LabelEncoder()
dataset['examide']=l_examide.fit_transform(dataset['examide'])
l_insulin=LabelEncoder()
dataset['insulin']=l_insulin.fit_transform(dataset['insulin'])
l_glipizide_metformin=LabelEncoder()
dataset['glipizide.metformin']=l_glipizide_metformin.fit_transform(dataset['glipizide.metformin'])
l_diabetesMed=LabelEncoder()
dataset['diabetesMed']=l_diabetesMed.fit_transform(dataset['diabetesMed'])
l_readmitted=LabelEncoder()
dataset['readmitted']=l_readmitted.fit_transform(dataset['readmitted'])

In [206]:
dataset

,race,gender,age,time_in_hospital,specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,examide,insulin,glipizide.metformin,diabetesMed,readmitted
0,2,0,55,1,0,35,4,21,0,0,0,9,0,1,0,0,0
1,2,0,25,2,1,8,5,5,0,0,0,6,0,1,0,0,0
3,0,0,55,4,1,33,1,5,0,0,0,3,0,2,0,1,0
4,0,0,55,5,0,31,0,13,0,0,0,7,0,2,0,1,0
5,2,1,75,4,0,29,0,10,0,0,0,8,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,0,65,3,1,30,1,29,0,0,0,7,0,1,0,1,0
9996,0,1,65,8,0,1,5,15,0,0,0,9,0,2,0,1,0
9997,0,0,75,13,0,46,2,14,0,0,1,6,0,1,0,0,1
9998,2,1,85,2,0,62,1,7,0,0,3,9,0,1,0,0,0
9999,2,1,75,8,1,61,0,18,0,0,1,9,0,1,0,1,0

In [207]:
dataset['specialty'].unique

<bound method Series.unique of 0       0
1       1
3       1
4       0
5       0
       ..
9995    1
9996    0
9997    0
9998    0
9999    1
Name: specialty, Length: 8098, dtype: int32>

In [208]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import xgboost as xgb

In [209]:
X=dataset.drop(['readmitted'],axis=1)
Y=dataset['readmitted']
dataset['race'].value_counts()

2    5855
0    1787
4     284
3     129
1      43
Name: race, dtype: int64

In [210]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=42)

In [211]:
model1=RandomForestClassifier(n_estimators=1000)

In [212]:
model2=xgb.XGBClassifier()

In [213]:
model1.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=1000)

In [214]:
predictions=model1.predict(X_train)
accuracy=accuracy_score(predictions,Y_train)
accuracy

0.9998627881448957

In [215]:
predictions1=model1.predict(X_test)

In [216]:
accuracy=accuracy_score(predictions1,Y_test)
accuracy

0.6271604938271605

In [217]:
import pickle

In [218]:
dataset={"classifier":model1,"l_race":l_race,"l_gender":l_gender,"l_specialty":l_specialty,"l_examide":l_examide,"l_insulin":l_insulin,
        "l_glipizide_metformin":l_glipizide_metformin,"l_diabetesMed":l_diabetesMed}

In [219]:
with open('saved_steps1.pkl','wb') as file:
    pickle.dump(dataset,file)

In [220]:
with open ('saved_steps1.pkl','rb') as file:
    data=pickle.load(file)
    
classifier=dataset["classifier"]